cart/urls.py
from django.urls import path
from .import views

 
app_name='cart'

urlpatterns=[
    path('', views.carts,name='carts'),
    path('addToCart/<int:product_id>/',views.addToCart,name='addToCart'),
    path('removeFromCart/<int:product_id>/',views.removeFromCart,name='removeFromCart'),
    path('deleteFromCart/<int:product_id>/',views.deleteFromCart,name='deleteFromCart'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from members import views
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls',namespace='sotre')),
    path('home/',include('store.urls',namespace='sotre')),
    path('members/',include('members.urls',namespace='members')),
    path('cart/',include('cart.urls',namespace='cart')),
    #path('register/',views.register, name='register'),
    
   
    ]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

#if settings.DEBUG:
    #urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/urls.py
from django.shortcuts import render
from django.urls.conf import path
from django.urls.resolvers import URLPattern
from . import views
# Create your views here.


app_name='store'

urlpatterns=[
    
      path('',views.storeProducts, name='storeProducts'),
       
      #<slug refers to datatype want to stored and pass :
      # /item/chef-weslen/
      path('product/<slug:slug>/',views.productDetail, name='productDetail'),
     
      path('category/<slug:category_slug>/',views.productCategory, name='productCategory'),
      
      path('search/', views.searchResult, name='searchResult')
    
]

cart/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from django.db.models.fields import BooleanField, FloatField
from django.db.models.fields.related import ForeignKey

from store.models import Product
 

# Create your models here.

'''class Order(models.Model):
    member=Model.ForeignKey(members,on_delete=models.CASCADE)
    Order_product=models.BooleanField(default=False)
    total_price=models.FloatField(default=0)
    
    def __str__(self):
        return self.cart_ID'''
    
class Cart(models.Model):
    cart_ID=models.CharField(max_length=255,blank=True)
    date_added=models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.cart_ID
    
class CartProduct(models.Model):
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantiy=models.IntegerField()
    created=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.product
    
    def total_price(self):
        return self.quantiy*self.product.price 
    
     
     

cart/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from store.models import Product
from .models import Cart, CartProduct
from django.contrib.auth.decorators import login_required

# Create your views here.


def cartID(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart    
        
 
def addToCart(request,product_id):
    product=Product.objects.get(id=product_id)#get the product
    try:
        cart=Cart.objects.get(cart_ID=cartID(request)) # get the cart using cartID using session 
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_ID=cartID(request)
        )    
    cart.save()
    
    try:
        cart_product=CartProduct.objects.get(product=product,cart=cart)
        cart_product.quantiy+=1 # card_item quantiy
        cart_product.save()
    except CartProduct.DoesNotExist:
        cart_product=CartProduct.objects.create(
            product=product,
            quantiy=1,
            cart=cart,
        )
        cart_product.save()
  
    return redirect('cart:carts')


def removeFromCart(request,product_id):
    product=Product.objects.get(id=product_id)#get the product
    cart=Cart.objects.get(cart_ID=cartID(request)) # get the cart using cartID using session 
    cart_product=CartProduct.objects.get(product=product,cart=cart)
    
    
    if cart_product.quantiy>1:
        cart_product.quantiy-=1 # card_item quantiy
        cart_product.save()
    else:
        cart_product.delete()
           
    return redirect('cart:carts')


def deleteFromCart(request,product_id):
    
    product=Product.objects.get(id=product_id)#get the product
    cart=Cart.objects.get(cart_ID=cartID(request)) # get the cart using cartID using session 
    cart_product=CartProduct.objects.get(product=product,cart=cart)
    cart_product.delete()
    
    return redirect('cart:carts')
    
    
def carts(request,total=0,quantiy=0,discount=0,payable=0,cart_product=None):

    try:
        carts=Cart.objects.get(cart_ID=cartID(request))
        cart_products=CartProduct.objects.filter(cart=carts)
        for cart_product in cart_products:
            total=total+(cart_product.product.price*cart_product.quantiy)
            discount=discount +(cart_product.product.discount*cart_product.quantiy)
            quantiy+=cart_product.quantiy
            payable=total-discount
    except ObjectDoesNotExist:
        pass
    
    context={
        'discount':discount,
        'total': total,
        'quantiy': quantiy,
        'cart_products':cart_products,
        'payable':payable,

    }        
    return render(request,'cart.html',context)

templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

 
<title>{% block title %} E-Commerce {% endblock %}</title>

<!--to change the web Icon--> 
<link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">

<!-- jQuery -->
<script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src="{% static 'js/bootstrap.bundle.min.js' %} " type="text/javascript"></script>
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="{% static 'fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)" />

<!-- custom javascript -->
<script src="{% static 'js/script.js' %}" type="text/javascript"></script>



<script type="text/javascript">
/// some script

// jquery ready start
$(document).ready(function() {
	// jQuery code

}); 
// jquery end
</script>

</head>
<body>
   <!-- navbar-->
   {% include './navbar.html'%}
    {% block content %}
    <!-- content -->
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endblock %}
    <!--footer-->
    {% include './footer.html'%}

templates/cart.html
<!--check whats the difference between include and extend-->
{% extends 'base.html' %}

{% load static %}

{% block content %}


<!-- ============================ COMPONENT 1 ================================= -->

<div class="row">
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>
	{% for cart_product in cart_products %}
		<tr>
			<td>
				<figure class="itemside align-items-center">
					<div class="aside"><img src="{{cart_product.product.image.url}}" class="img-sm"></div>
					<figcaption class="info">
						<a href="#" class="title text-dark">{{cart_product.product.title}}</a>
						<p class="text-muted small">Matrix: 25 Mpx <br> Brand: Canon</p>
					</figcaption>
				</figure>
			</td>
			<td> 
				<!-- col.// -->
							<div class="col"> 
								<div class="input-group input-spinner">
									<div class="input-group-prepend">
									<a href="{% url 'cart:removeFromCart' cart_product.product.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
									</div>
									<input type="text" class="form-control"  value="{{cart_product.quantiy}}">
									<div class="input-group-append">
									<a href="{% url 'cart:addToCart' cart_product.product.id %}" class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-plus"></i> </a>
									</div>
								</div> <!-- input-group.// -->
							</div> <!-- col.// -->
			</td>
			<td> 
				<div class="price-wrap"> 
					<var class="price">{{cart_product.total_price}}</var> 
					<small class="text-muted">{{cart_product.product.price}}</small> 
				</div> <!-- price-wrap .// -->
			</td>
			<td class="text-right"> 
			<a href="{% url 'cart:deleteFromCart'  cart_product.product.id %}" class="btn btn-danger"> Remove</a>
			</td>
		</tr>
	{% endfor %}	

</tbody>
</table>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">RM {{total}}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>saved:</dt>
			  <dd class="text-right">RM {{discount}}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Total:</dt>
			  <dd class="text-right text-dark b"><strong>RM {{payable}}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="./images/misc/payments.png" height="26">
			</p>
			<a href="./place-order.html" class="btn btn-primary btn-block"> Checkout </a>
			<a href="./store.html" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

{%endblock%}    

templates/category.html
 
<!--check whats the difference between include and extend-->
{% extends 'base.html' %}

{% load static %}

{% block content %}

 
 <!-- ========================= SECTION MAIN ========================= -->
<section class="section-intro padding-y-sm">
<div class="container">



</div> <!-- container //  -->
</section>
<!-- ========================= SECTION MAIN END// ========================= -->

<!-- ========================= SECTION  ========================= -->
<section class="section-name padding-y-sm">
<div class="container">

 
<header class="border-bottom mb-4 pb-3">
    <div class="form-inline">
        <span class="mr-md-auto">{{products.count}} Items Found </span>
        
    </div>
</header><!-- sect-heading -->
	
<div class="row">
    {% for product in products %}
        <div class="col-md-3">
            <div class="card card-product-grid">
                
                    <a href="{{productDetail.html}}" class="img-wrap"> <img src="{{product.image.url}}"> </a>
                    <figcaption class="info-wrap">
                        <a href="{{product.getProductDetail}}" class="title">{{product.title}}</a>
                        <div class="price mt-1">RM{{product.price}}</div> <!-- price-wrap.// -->

                        <div class="rating-star">
							<span>
								<i class="fa fa-star{% if product.averageReview < 0.5 %}-o{% elif product.averageReview >= 0.5 and product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
								<i class="fa fa-star{% if product.averageReview < 1.5 %}-o{% elif product.averageReview >= 1.5 and product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
								<i class="fa fa-star{% if product.averageReview < 2.5 %}-o{% elif product.averageReview >= 2.5 and product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
								<i class="fa fa-star{% if product.averageReview < 3.5 %}-o{% elif product.averageReview >= 3.5 and product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
								<i class="fa fa-star{% if product.averageReview < 4.5 %}-o{% elif product.averageReview >= 4.5 and product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
								</span>
						</div>
                    </figcaption>
                
            </div>  
        </div> <!-- col.// -->
    {% endfor %}  
	 
</div> <!-- row.// -->

</div><!-- container // -->
</section>
    <!-- ========================= SECTION  END// ========================= -->
{%endblock%}    
 

 

    
    
     

templates/footer.html
<!-- ========================= FOOTER ========================= -->
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-2">
				<p class="text-muted"> &copy 2021 PingLun </p>
			</div>
			<div class="col-md-8 text-md-center">
				<span  class="px-2">info@pixsellz.io</span>
				<span  class="px-2">+879-332-9375</span>
				<span  class="px-2">Street name 123, Avanue abc</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->

templates/home.html
<!--check whats the difference between include and extend-->
{% extends 'base.html' %}

{% load static %}

{% block content %}



<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
	<div class="container">
		<h2 class="title-page">My Culinary Store</h2>
		
	</div> <!-- container //  -->
	</section>
	<!-- ========================= SECTION INTRO END// ========================= -->
	
	<!-- ========================= SECTION  ========================= -->
<section class="section-name padding-y-sm">
	<div class="container">
	
	 
	<header class="border-bottom mb-4 pb-3">
		<div class="form-inline">
			<span class="mr-md-auto">{{products.count}} Items Found </span>
			
		</div>
	</header><!-- sect-heading -->
		
	<div class="row">
		{% for product in products %}
			<div class="col-md-3">
				<div class="card card-product-grid">
					
						<a href="{{productDetail.html}}" class="img-wrap"> <img src="{{product.image.url}}"> </a>
						<figcaption class="info-wrap">
							<a href="{{product.getProductDetail}}" class="title">{{product.title}}</a>
							<div class="price mt-1">RM{{product.price}}</div> <!-- price-wrap.// -->
							<!--<div class="line-through">RM{{product.discount}}</div> <!-- price-wrap.// -->
	
							<div class="rating-star">
								<span>
									<i class="fa fa-star{% if product.averageReview < 0.5 %}-o{% elif product.averageReview >= 0.5 and product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if product.averageReview < 1.5 %}-o{% elif product.averageReview >= 1.5 and product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if product.averageReview < 2.5 %}-o{% elif product.averageReview >= 2.5 and product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if product.averageReview < 3.5 %}-o{% elif product.averageReview >= 3.5 and product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if product.averageReview < 4.5 %}-o{% elif product.averageReview >= 4.5 and product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
									</span>
							</div>
						</figcaption>
					
				</div>  
			</div> <!-- col.// -->
		{% endfor %}  
		 
	</div> <!-- row.// -->
	
	</div><!-- container // -->
	</section>
		<!-- ========================= SECTION  END// ========================= -->
	{%endblock%}    

templates/navbar.html
{% load static  %}

<header class="section-header">
    <nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
       
    </div> <!-- container //  -->
    </nav>
    
    <section class="header-main border-bottom">
        <div class="container">
    <div class="row align-items-center">
        <div class="col-lg-2 col-md-3 col-6">
            <a href="/home" class="brand-wrap">
                <img class="logo" src="{% static './images/Chef.png' %}">
            </a> <!-- brand-wrap.// -->
        </div>
        <div class="col-lg col-sm col-md col-6 flex-grow-0">
            <div class="category-wrap dropdown d-inline-block float-right">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> 
                    <i class="fa fa-bars"></i> All category 
                </button>
                <div class="dropdown-menu">
                    {% for type in categories %}
                    <a class="dropdown-item" href="{{type.getProductCategory}}">{{ type.category_name }}  </a>
                    {% endfor %}
                    
                </div>
            </div>  <!-- category-wrap.// -->
        </div> <!-- col.// -->
        
        <div class="col-lg  col-md-6 col-sm-12 col">
            <!-- store is the name specified in urls as app_name, add thie to avoid error  "Reverse for '' not found. '' is not a valid view function or pattern name."
            get from : https://www.tutorialguruji.com/python/django-reverse-for-index-not-found-index-is-not-a-valid-view-function-or-pattern-name/-->
            <form class="searched" method="POST" action="{% url 'store:searchResult' %}">
                
                {% csrf_token %}

                <div class="input-group w-100">
                    <input type="search" class="form-control" name="find" style="width:60%;" placeholder="Search Product">
                    
                    <div class="input-group-append">
                     
                        <button class="btn btn-primary" type="submit">
                        <i class="fa fa-search"></i>
                      </button>
                    </div>
                </div>
            </form> <!-- search-wrap .end// -->
        </div> <!-- col.// -->
        <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                    <div class="d-flex justify-content-end mb-3 mb-lg-0">
                        <div class="widget-header">
                            <small class="title text-muted">Welcome {{request.user}}!</small>
                            <div>  
                             
                              {% if request.user.is_authenticated %}  
                                <a href="{% url 'members:logout' %}"> logout</a>
                                <small class="title text-muted">Welcome {{user.get_username}}!</small>
                              {% else %}  
                                <!--login is the defaul name-->
                                <a href="{% url 'members:login' %}">Sign in</a> 
                                <small class="title text-muted">Welcome {{request.user}}!</small> 
                              {% endif%} 
                            </div>
                        </div>
                        <a href="{% url 'cart:carts' %}" class="widget-header pl-3 ml-3">
                            <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                            <span class="badge badge-pill badge-danger notify">{{cart_productNo}}</span>
                        </a>
                    </div> <!-- widgets-wrap.// -->
                </div> <!-- col.// -->
    </div> <!-- row.// -->
        </div> <!-- container.// -->
    </section> <!-- header-main .// -->
    
    
    
    
    </header> <!-- section-header.// -->

templates/productDetail.html
<!--check whats the difference between include and extend-->
{% extends 'base.html' %}

{% load static %}

{% block content %}



<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
    <article class="gallery-wrap"> 
        <div class="img-big-wrap">
           <a href="#"><img src="{{ product.image.url }}"></a>
        </div> <!-- img-big-wrap.// -->
        
    </article> <!-- gallery-wrap .end// -->
            </aside>
            <main class="col-md-6 border-left">
    <article class="content-body">
    
    <h2 class="title">{{product.title}}</h2>
    
    <div class="mb-3"> 
        <var class="price h4">RM{{product.price}}</var> 
    </div> 
    
    <p>{{product.description}}</p>
    
    
    <hr>
        <div class="row">
            <div class="item-option-select">
                <h6>Choose Color</h6>
                <div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
                  <label class="btn btn-light">
                    <input type="radio" name="radio_color"> Silver
                  </label>
                  <label class="btn btn-light">
                    <input type="radio" name="radio_color" > Gray
                  </label>
                  <label class="btn btn-light active">
                    <input type="radio" name="radio_color checked"> Gold
                  </label>
                  <label class="btn btn-light">
                    <input type="radio" name="radio_color"> Black
                  </label>
                </div> 
            </div>
        </div> <!-- row.// -->
        <div class="row">
            <div class="item-option-select">
                <h6>Select Size</h6>
                <div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
                  <label class="btn btn-light">
                    <input type="radio" name="radio_color"> S
                  </label>
                  <label class="btn btn-light active">
                    <input type="radio" name="radio_color" checked> M
                  </label>
                  <label class="btn btn-light">
                    <input type="radio" name="radio_color"> L
                  </label>
                  <label class="btn btn-light">
                    <input type="radio" name="radio_color"> XL
                  </label>
                </div> 
            </div>
        </div> <!-- row.// -->
        <hr>
        
        {% if not product.in_stock  %}
          <h5 class="text-danger">Out of stock</h5>
        {% else %}   
          <a href="{% url 'cart:addToCart' product.id %}" class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </a>
        {% endif%} 

    </article> <!-- product-info-aside .// -->
            </main> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    <br>
    
    <div class="row">
                <div class="col-md-9">
    
        <header class="section-heading">
            <h3>Customer Reviews </h3>  
            
        </header>
    
        <article class="box mb-3">
            <div class="icontext w-100">
                <img src="./images/avatars/avatar1.jpg" class="img-xs icon rounded-circle">
                <div class="text">
                    <span class="date text-muted float-md-right">24.04.2020 </span>  
                    <h6 class="mb-1">Mike John </h6>
                    
                </div>
            </div> <!-- icontext.// -->
            <div class="mt-3">
                <p>
                    Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip
                </p>	
            </div>
        </article>
    
        
    
        </div> <!-- col.// -->
    </div> <!-- row.// -->
    
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    

{% endblock %}

templates/searchResult.html
 
<!--check whats the difference between include and extend-->
{% extends 'base.html' %}

{% load static %}

{% block content %}

 
<!-- ========================= SECTION MAIN ========================= -->
<!-- ========================= SECTION MAIN ========================= -->
<section class="section-intro padding-y-sm">
<div class="container">

<div class="intro-banner-wrap">
	<img src="images/banners/1.jpg" class="img-fluid rounded">
</div>

</div> <!-- container //  -->
</section>
<!-- ========================= SECTION MAIN END// ========================= -->

<!-- ========================= SECTION  ========================= -->
<section class="section-name padding-y-sm">
<div class="container">

<header class="section-heading">
	<a href="./store.html" class="btn btn-outline-primary float-right">See all</a>
	 
</header><!-- sect-heading -->

	 
    {% if searched %}
    <h3>Search for "{{searched}}"</h3>
        <div class="row">
        {% for item in items %}
            <div class="col-md-3">
                <div class="card card-product-grid">
                    
                        <a href="{{item.getProductDetail}}" class="img-wrap"> <img src="{{item.image.url}}"> </a>
                        <figcaption class="info-wrap">
                            <a href="{{item.getProductDetail}}" class="title">{{item.title}}</a>
                            <div class="price mt-1">RM{{item.price}}</div> <!-- price-wrap.// -->
                        </figcaption>
                    
                </div>  
            </div> <!-- col.// -->
        {%endfor %}  
        
        </div> <!-- row.// -->

        </div><!-- container // -->
        {% else %}
        
        <h1>Please Input</h1>

    {% endif%}  
</section>
    <!-- ========================= SECTION  END// ========================= -->
{%endblock%}    